spring:
  data.mongodb:
    uri: mongodb://root:password1234@localhost:27017/orderdb?authSource=admin
    database: orderdb
  kafka:
    bootstrap-servers: localhost:29092,localhost:29093,localhost:29094
    consumer:
      key-deserializer: org.apache.kafka.common.serialization.IntegerDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties.spring.json.trusted.packages: '*'
    template:
      default-topic: orders

server.port: 9080