
spring:
  data.mongodb:
    uri: mongodb://root:password1234@localhost:27017/orderdb?authSource=admin
    database: ordersdb
  kafka:
    bootstrap-servers: localhost:29092,localhost:29093,localhost:29094
    #listener:
      #ack-mode: manual
    producer:
      key-serializer: org.apache.kafka.common.serialization.IntegerSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      key-deserializer: org.apache.kafka.common.serialization.IntegerDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      group-id: consumer02
      #auto-offset-reset: earliest
      #auto-offset-reset: latest
      properties:
        #enable.auto.commit: false
        spring.json.trusted.packages: '*'
    #listener:
      #concurrency: 3
server:
  port: 9080